config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard"

  # Defines the root path route ("/")
  # root "posts#index"
  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update]
end

app/views/pages/dashboard.html.erb
<style>
  .nav-link {
    font-family: 'Roboto', sans-serif;
    font-weight: bold;
    /* You can adjust other text properties here */
  }
</style>

<ul class="nav nav-tabs">
  <li class="nav-item">
      <a class="nav-link active" data-bs-toggle="tab" href="#mycarsSection">MY CARS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#rentedcarsSection">RENTED CARS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#bookingsSection">MY BOOKINGS</a>
    </li>
</ul>


  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="tab-content">

          <div class="tab-pane fade show active" id="mycarsSection">
            <div class="cars">
              <div class="d-flex justify-content-between mb-2 p-3 align-items-center">
                <h3 class="card-title">MY CARS</h3><br>
                <h5><%= link_to "Add a Car", new_car_path, class:"btn btn-outline-dark"%></h5>
              </div>
              <div class="card-body cards mb-4" style="border-radius: 5px">
              <% @cars.each do |car| %>
                  <div class="cars-card card-category d-flex flex-column cards mb-4" style="border-radius: 5px">
                    <%= link_to car_path(car) do %>
                      <div class="row">
                        <!-- Column for the list -->
                        <div class="col-md-6">
                          <ul class="list-unstyled">
                            <li><i class="fas fa-car"></i> <%= car.model %> </li>
                            <li><i class="fa-solid fa-circle-info"></i> <%= car.description %> </li>
                            <li><i class="fas fa-paint-brush"></i> <%= car.color %> </li>
                            <li><i class="fas fa-gas-pump"></i> <%= car.fuel %> </li>
                            <li><i class="fas fa-dollar-sign"></i> <%= car.price %>/day </li>
                          </ul>
                        </div>
                        <!-- Column for the picture -->
                        <div class="col-md-6">
                        <% if car.photos.present? %>
                          <div class="d-flex justify-content-end align-items-center mb-2">
                            <% photo = car.photos.first %>
                            <div class="overflow-hidden p-0" style="border-radius: 5px;">
                              <%= cl_image_tag photo.key, height: 150, width: 170, crop: :fill %>
                            </div>
                          </div>
                        <% end %>
                        </div>
                      </div>
                      <div class="d-flex justify-content-between mt-auto">
                        <%= link_to "Update", edit_car_path(car), class: "btn btn-primary" %>
                      </div>
                    <% end %>
                  </div>
              <% end %>
              </div>
            </div>
          </div>

          <div class="tab-pane fade show" id="bookingsSection">
            <div class="col-lg-12">
            <!-- My Bookings Card -->
            <div class="bookings mb-2 p-3 align-items-center">
              <h3 class="card-title">MY BOOKINGS</h3><br>
              <div class="card-body cards mb-4" style="border-radius: 5px">
                <% @bookings.each do |booking| %>
                  <div class="bookings-card card-category d-flex flex-column cards" style="border-radius: 5px">
                    <div class="row">
                      <ul class="list-unstyled col-md-7">
                        <li></li>
                        <li><i class="far fa-calendar"></i><strong> Date: </strong><%= booking.start_date %><strong> to </strong><%= booking.end_date %></li><br>
                        <li><i class="fas fa-car"></i><%= booking.car.model %> </li>
                        <li><i class="fas fa-map-marker-alt"></i><%= booking.car.address %> </li>
                        <li><i class="fas fa-user"></i> Owner: <%= booking.car.user.first_name %> <%= booking.car.user.last_name %> </li>
                        <li><i class="fas fa-dollar-sign"></i> <%= booking.total_price %> </li>
                      </ul>
                      <div class="col-md-5">
                        <div class="d-flex justify-content-end align-items-center mb-2">
                          <div class="overflow-hidden p-0" style="border-radius: 5px;">
                            <img src="https://source.unsplash.com/random/150x150/?car-<%= "#{booking.car.model}" %>" alt="car picture">
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>
                      <i class="fas fa-info-circle"></i> Status: <%= booking.status %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            </div>
            </div>


          <div class="tab-pane fade show" id="rentedcarsSection">
            <div class="rented-cars mb-2 p-3 align-items-center">
            <h3 class="card-title">CARS RENTED</h3><br>
            <div class="card-body cards mb-4" style="border-radius: 5px">
              <% @cars.each do |car| %>
                <% car.bookings.each do |booking| %>
                  <div class="rented-cars-card card-category d-flex flex-column cards" style="border-radius: 5px">
                    <div class="row">
                      <div class="col-md-7">
                        <ul class="list-unstyled">
                          <li><i class="fas fa-car"></i> Car rented: <%= car.model %> </li>
                          <li><i class="fas fa-user"></i> Renter: <%= booking.user.first_name %> <%= booking.user.last_name %> </li>
                        </ul>
                        <div>
                          <i class="fas fa-info-circle"></i> Status:
                          <% case booking.status %>
                            <% when 'Accepted' %>
                              <%= link_to booking.status, edit_booking_path(booking), class: "btn btn-success", style: "border-radius: 5px; font-weight: bold;" %>
                            <% when 'Rejected' %>
                              <%= link_to booking.status, edit_booking_path(booking), class: "btn btn-danger", style: "border-radius: 5px; font-weight: bold;" %>
                            <% when 'Pending' %>
                              <%= link_to booking.status, edit_booking_path(booking), class: "btn btn-warning", style: "border-radius: 5px; font-weight: bold;" %>
                            <% when 'Cancelled' %>
                              <%= link_to booking.status, edit_booking_path(booking), class: "btn btn-secondary", style: "border-radius: 5px; font-weight: bold;" %>
                            <% when 'Finalized' %>
                              <%= link_to booking.status, edit_booking_path(booking), class: "btn btn-light", style: "border-radius: 5px; font-weight: bold;" %>
                            <% else %>
                              <%= link_to booking.status, edit_booking_path(booking), class: "btn btn-primary", style: "border-radius: 5px; font-weight: bold;" %>
                          <% end %>
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="d-flex justify-content-end align-items-center mb-2">
                          <div class="overflow-hidden p-0" style="border-radius: 5px;">
                            <img src="https://source.unsplash.com/random/150x150/?car-<%= "#{booking.car.model}" %>" alt="car picture">
                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
                <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

<div class="cars-container-home mt-5">
  <div class="row">
    <div class="col-12">
      <div class="row mt-5 cards-grid">
         <% @cars.each do |car| %>
          <div class= "col-3 mb-4">

            <div class="card h-100">
              <% if car.photos.present? %>
                <% photo = car.photos.first %>
                <%= cl_image_tag photo.key, transformation: { fetch_format: :auto, w: 800, h: 600, crop: :fill, gravity: :auto }, alt: "car picture", class: "img-sizing-home" %>
              <% else %>
                <img src="https://source.unsplash.com/random/800x600/?car-<%= "#{car.model}" %>" alt="car picture" class="img-sizing-home">
              <% end %>
              <p class="model-text-homepage mt-2"> <%= car.model %> </p>
              <p class="card-text-homepage"> Price: <%= car.price %>$/day </p>
              <div class="d-flex justify-content-between align-items-center mb-4" >
                <%= link_to 'More infos', car_path(car), class: 'link-home' %>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>